Repository aritroCoder/MoreTrees, pull requests merged in 2022-12, with the labels that each got.

#11 Plant Tree designed
  package.json
  pages/api/middleware/db.js
  pages/index.js
  pages/login.js
  pages/plantTree.js
  public/banana-icon.svg
  public/cactus-plant-icon.svg
  public/icons8-eucalyptus-64.png
  public/icons8-lemon-60.png
  public/mango-fruit-icon.svg
  public/pear-icon.svg
  public/pomegranate-fruit-icon.svg
  styles/plantTree.module.css
Labels: points:10, codepeak 22

#13 Added plant information
  components/Navbar/Navbar.js
  pages/index.js
  pages/plantTree.js
  pages/profile.js
  styles/Home.module.css
  styles/Profile.module.css
Labels: codepeak 22, points:30

#15 added responsive contact us page with real time map feature
  pages/_app.js
  pages/contact.js
  styles/contact.module.css
Labels: codepeak 22, points:5

#31 blog_page created
  components/Navbar/Navbar.js
  package.json
  pages/blog.js
  pages/signup.js
  styles/Home.module.css
  styles/globals.css
  yarn.lock
Labels: points:10, codepeak 22
